// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGmE8Z-U5k41lq96BPLN4DVYB_tPx2sJA',
    appId: '1:730430895323:android:fafb7d4f0b1253961208fe',
    messagingSenderId: '730430895323',
    projectId: 'cybershield-mobileintern-78da8',
    storageBucket: 'cybershield-mobileintern-78da8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPTjOODxFRJhPK1S9QFGS-qmIt5PWEnZY',
    appId: '1:730430895323:ios:1a4d7641e5232b931208fe',
    messagingSenderId: '730430895323',
    projectId: 'cybershield-mobileintern-78da8',
    storageBucket: 'cybershield-mobileintern-78da8.firebasestorage.app',
    androidClientId: '730430895323-8t3dtqgcoj1cis54bqggq8v4o0vrari6.apps.googleusercontent.com',
    iosClientId: '730430895323-jrpv2o7di2r3d1ru030k9pttochpn685.apps.googleusercontent.com',
    iosBundleId: 'com.example.cybershieldApp',
  );
}
